### ISSUE TITLE
Implement Tree Traversal Algorithms

### ISSUE THREAD

**Issue by maheshmnj** [saurabh47/Popular_Coding_Questions_Solution#5]
Missing: Tree Traversals (Inorder, Preorder and Postorder) implementation

more on tree traversal can be found here:https://en.wikipedia.org/wiki/Tree_traversal#Types

**Comment by MansiAyer** [comment]
hi, may I take up this issue?

**Comment by saurabh47** [comment]
@MansiAyer yes,Implement all the Tree Traversals & send pull request

**Comment by MansiAyer** [comment]
👍
