### ISSUE TITLE
Implement caesar cipher encryption

### ISSUE THREAD

**Issue by saurabh47** [saurabh47/Popular_Coding_Questions_Solution#7]
Given a non-empty string of lowercase letters and a non-negative integer representing a key, write a function that returns a new string obtained by
shifting every letter in the input string by k positions in the alphabet, where k is the key.
Note that letters should "wrap" around the alphabet; in other words,
the letter **z* shifted by one returns the letter **a**

**Sample Input**
```
string = "abz"
key = 2
```
**Sample Output**
```
"cdb"
```

**Comment by Karthik-B-06** [comment]
I will take this up. Can you assign it to me ?

**Comment by saurabh47** [comment]
@Karthik-B-06 assign to you. Send your pull request.

**Comment by Aditya489** [comment]
can you assign this to me , i would like to work on this!

**Comment by saurabh47** [comment]
@Aditya489 This problem already solved in `c` language.you send improved version of this code or you solve same problem in different programming language & send the pull request.

**Comment by Aditya489** [comment]
its already closed i did it in another programming language , can i submit now?

**Comment by saurabh47** [comment]
@Aditya489 You can send pull request.
